import {
  useEffect, useId, useRef, useState, type ReactElement,
} from 'react';
import { imageUrl, type QuestionEntry } from '../questions.ts';
import { GenerationLabel } from './GenerationDetails.tsx';
import './ComparisonArtwork.css';

const LETTERS = ['A', 'B', 'C', 'D'];

type ComparisonArtworkProps = {
  images: QuestionEntry[];
  options: string[];
  selected: string | null;
  revealedAnswer: string | null;
  eliminated: string[];
};

type ComparisonImageProps = {
  src: string;
  label: string;
  preview?: boolean;
};

function ComparisonImage({ src, label, preview = false }: ComparisonImageProps): ReactElement {
  const [failed, setFailed] = useState(false);

  return failed ? (
    <span className="mil-comparison-unavailable" role="img" aria-label={`${label} unavailable`}>
      <svg viewBox="0 0 40 40" fill="none" stroke="currentColor" strokeWidth="1.25" aria-hidden="true">
        <rect x="4" y="4" width="32" height="32" rx="2" />
        <circle cx="26" cy="14" r="3" />
        <path d="m4 29 10-11 10 12 5-5 7 7" />
      </svg>
      <span>Image unavailable</span>
    </span>
  ) : (
    <img
      data-testid={preview ? undefined : 'comparison-image'}
      className="mil-comparison-image"
      src={src}
      alt={label}
      onError={() => setFailed(true)}
    />
  );
}

function ComparisonArtwork({
  images,
  options,
  selected,
  revealedAnswer,
  eliminated,
}: ComparisonArtworkProps): ReactElement {
  const id = useId();
  const dialogRef = useRef<HTMLDialogElement>(null);
  const closeRef = useRef<HTMLButtonElement>(null);
  const triggerRef = useRef<HTMLButtonElement | null>(null);
  const roundKey = images.map((entry) => imageUrl(entry.modelName, entry.image)).join('|');
  const [opened, setOpened] = useState<{ index: number; roundKey: string } | null>(null);
  const previewIndex = opened?.roundKey === roundKey ? opened.index : null;
  const previewEntry = previewIndex === null ? undefined : images[previewIndex];
  const isRevealed = revealedAnswer !== null;
  const prompt = images[0]?.prompt;

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;

    if (previewEntry && !dialog.open) {
      dialog.showModal();
      closeRef.current?.focus();
    } else if (!previewEntry && dialog.open) {
      dialog.close();
    }
  }, [previewEntry]);

  const closePreview = () => {
    setOpened(null);
    if (triggerRef.current?.isConnected) triggerRef.current.focus();
  };

  return (
    <div className="mil-comparison" data-testid="comparison-artwork">
      <p className="mil-comparison-instruction" id={`${id}-instruction`}>
        Same prompt, four models. Tap to enlarge.
      </p>

      <div className="mil-comparison-grid">
        {images.map((entry, index) => {
          const letter = LETTERS[index];
          const option = options[index];
          const isSelected = selected === option;
          const isCorrect = revealedAnswer !== null && revealedAnswer === option;
          const isEliminated = eliminated.includes(option);
          const src = imageUrl(entry.modelName, entry.image);
          const classes = [
            'mil-comparison-tile',
            isSelected && !isCorrect ? 'mil-comparison-selected' : '',
            isCorrect ? 'mil-comparison-correct' : '',
            isEliminated ? 'mil-comparison-eliminated' : '',
          ].filter(Boolean).join(' ');

          return (
            <button
              key={src}
              type="button"
              className={classes}
              aria-label={`Enlarge image ${letter}`}
              aria-haspopup="dialog"
              aria-describedby={isRevealed ? `${id}-caption-${index}` : `${id}-instruction`}
              onClick={(event) => {
                triggerRef.current = event.currentTarget;
                setOpened({ index, roundKey });
              }}
            >
              <span className="mil-comparison-picture">
                <ComparisonImage
                  key={src}
                  src={src}
                  label={isRevealed ? `Image ${letter}, generated by ${entry.modelName}` : `Image ${letter}`}
                />
                <span className="mil-comparison-letter" aria-hidden="true">{letter}</span>
                <svg className="mil-comparison-expand" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true">
                  <path d="M12 3h5v5M17 3l-5 5M8 17H3v-5M3 17l5-5" />
                </svg>
              </span>
              {isRevealed && (
                <span className="mil-comparison-caption" id={`${id}-caption-${index}`}>
                  <GenerationLabel entry={entry} />
                  {isCorrect && <span className="mil-comparison-result">Correct</span>}
                </span>
              )}
            </button>
          );
        })}
      </div>

      {prompt && prompt !== 'stub' && (
        <details key={roundKey} className="mil-artwork-prompt mil-comparison-prompt">
          <summary>View shared prompt</summary>
          <p>{prompt}</p>
        </details>
      )}

      <dialog
        ref={dialogRef}
        className="mil-image-preview"
        data-testid="image-preview"
        aria-labelledby={`${id}-preview-title`}
        onClose={closePreview}
      >
        <div className="mil-image-preview-header">
          <h2 id={`${id}-preview-title`}>
            {previewIndex === null ? 'Image preview' : `Image ${LETTERS[previewIndex]}`}
            {isRevealed && previewEntry && <GenerationLabel entry={previewEntry} />}
          </h2>
          <button ref={closeRef} type="button" onClick={() => dialogRef.current?.close()} aria-label="Close image preview">
            <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true">
              <path d="m5 5 10 10M15 5 5 15" />
            </svg>
            <span>Close</span>
          </button>
        </div>
        {previewEntry && previewIndex !== null && (
          <div className="mil-image-preview-picture">
            <ComparisonImage
              key={imageUrl(previewEntry.modelName, previewEntry.image)}
              src={imageUrl(previewEntry.modelName, previewEntry.image)}
              label={isRevealed ? `Image ${LETTERS[previewIndex]}, generated by ${previewEntry.modelName}` : `Image ${LETTERS[previewIndex]}`}
              preview
            />
          </div>
        )}
      </dialog>
    </div>
  );
}

export default ComparisonArtwork;
